{% set name = "beem" %}
{% set version = "0.24.21" %}
{% set sha256 = "27695bee5aeaa3848089f8dbea1dae43357e9399a7b6fa044d3fc7f55472597e" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256|lower }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - beempy = beem.cli:cli

requirements:
  host:
    - python >=3.6
    - pip
    - pytest-runner
    - setuptools
  run:
    - python >=3.6
    - ecdsa
    - requests
    - websocket-client
    - appdirs
    - scrypt
    - pycryptodomex
    - pytz
    - six
    - prettytable
    - click
    - click-shell
    - cryptography
    - ruamel.yaml
    - diff-match-patch
    - asn1crypto

test:
  imports:
    - beem
    - beem.account
    - beem.amount
    - beem.comment
    - beem.market
    - beem.block
    - beem.blockchain
    - beem.cli
    - beem.message
    - beem.instance
    - beem.price
    - beem.steem
    - beem.transactionbuilder
    - beem.utils
    - beem.vote
    - beem.witness

  commands:
    - beempy --help

about:
  home: https://github.com/holgern/beem
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  dev_url: https://github.com/holgern/beem
  doc_url: http://beem.readthedocs.io/en/latest/
  summary: beem is an unofficial python library for steem.

extra:
  recipe-maintainers:
    - holgern
