{% set name = "beem" %}
{% set version = "0.24.3" %}
{% set sha256 = "6768ce7b142c286b4f8a7417f0e39682ebc7f22bfdea6f200f49afb5e54a42cf" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256|lower }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - beempy = beem.cli:cli

requirements:
  build:
    - python
    - pip
    - pytest-runner
    - setuptools
  run:
    - python
    - future
    - ecdsa
    - requests
    - websocket-client
    - appdirs
    - events
    - scrypt
    - pycryptodomex
    - pytz
    - six
    - prettytable
    - click
    - click-shell
    - cryptography
    - pyyaml
    - diff-match-patch
    - asn1crypto

test:
  imports:
    - beem
    - beem.account
    - beem.amount
    - beem.comment
    - beem.market
    - beem.block
    - beem.blockchain
    - beem.cli
    - beem.message
    - beem.notify
    - beem.instance
    - beem.price
    - beem.steem
    - beem.transactionbuilder
    - beem.utils
    - beem.vote
    - beem.witness

  commands:
    - conda inspect linkages -p $PREFIX beem  # [not win]
    - conda inspect objects -p $PREFIX beem   # [osx]
    - beempy --help

about:
  home: https://github.com/holgern/beem
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  dev_url: https://github.com/holgern/beem
  doc_url: http://beem.readthedocs.io/en/latest/
  summary: beem is an unofficial python library for steem.

extra:
  recipe-maintainers:
    - holgern
