{% set name = "beem" %}
{% set version = "0.19.56" %}
{% set sha256 = "f0f8d4e0b801adf899d304e54b3b9f217491c15df7f0dd38adf93a3cd8314f68" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256|lower }}

build:
  number: 1
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .
  entry_points:
    - beempy = beem.cli:cli

requirements:
  build:
    - python
    - pip
    - pytest-runner
    - setuptools
  run:
    - python
    - future
    - ecdsa
    - requests
    - websocket-client
    - appdirs
    - events
    - scrypt
    - pycryptodomex
    - pytz
    - six
    - prettytable
    - click
    - cryptography

test:
  imports:
    - beem
    - beem.account
    - beem.amount
    - beem.comment
    - beem.market
    - beem.aes
    - beem.block
    - beem.blockchain
    - beem.cli
    - beem.message
    - beem.notify
    - beem.instance
    - beem.price
    - beem.steem
    - beem.transactionbuilder
    - beem.utils
    - beem.vote
    - beem.witness

  commands:
    - conda inspect linkages -p $PREFIX beem  # [not win]
    - conda inspect objects -p $PREFIX beem   # [osx]
    - beempy --help

about:
  home: https://github.com/holgern/beem
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  dev_url: https://github.com/holgern/beem
  doc_url: http://beem.readthedocs.io/en/latest/
  summary: 'beem is an unofficial python library for steem.'

extra:
  recipe-maintainers:
    - holgern
