travis:
  secure:
    BINSTAR_TOKEN: u+k7rB8luGwSxX6p4WKE50jdJ0IrVrA6f9x3IOxCtEbGbrSHq51PyqDNMEv4aUErhhX9uwhXWBQKUNVAZrvXgy9LydKD2Mt+sXIS66KgOqMc341NaOmuq986N2c4Cz69RUXIKRhaMSsVKGdJSBis37U6ZEGqxISX9HuxA+Mv3cxZPVXvA51f3c7uj4LwrzZRtWecqFDwlcX/xYX7QJuK5qaaiDMIqSXA18IYCeMO9QMG0su6Aa0sn18/wiDX+rkGwXQFvmRBsvFEt+WJrIdR3Gcsbwi4ypENoUwF92MDklHJVlLFfLcj1KGOiafwoMM5Klqx+1ZfVfOd3AAaQ6+dhkoyO9Xh/O1VTaBHwLFCSlt95MUC5/Ba9la484nYM3eJwUBhGOOh7Uxr3jULar1NXh7/IxTOa6C8AD1Fc9gVTjsKOflqcltIveJ5sbCPswuoN6YB+nIbvA42xk0wjXoFUXfZjycLXhB0DEAVVu9xw/QwRJ6gKPmiYT9V29jQB9o78BIyWwDXOA8BDzkBG4EYYWzRaL+UFTtSiF1uKUrUZBhE2uwACC1q/3ha7Hmanb4fh1Io9CKBUlboINfx/GxEd0YQxIrCNnqj3oEtDhtad6vIqKz30ofzHi0lUjAcmdHxFxZ8wV7HBOvaOIoEGAOvLJ9qZ1DQUFhlMdoDkTgSqu0=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
